"""added slugify fields

Revision ID: 2d754b3e6320
Revises: 4b6285828a0d
Create Date: 2013-07-24 21:01:51.121091

"""

# revision identifiers, used by Alembic.
revision = '2d754b3e6320'
down_revision = '4b6285828a0d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('post', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('tag', sa.Column('slug', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'slug')
    op.drop_column('post', 'slug')
    op.drop_column('category', 'slug')
    ### end Alembic commands ###
