"""updated post-comment relationship

Revision ID: 374bd75b2fad
Revises: 3175143dabb8
Create Date: 2013-07-20 09:31:36.843803

"""

# revision identifiers, used by Alembic.
revision = '374bd75b2fad'
down_revision = '3175143dabb8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'user_id')
    op.drop_column('comment', 'post_id')
    ### end Alembic commands ###
