"""updated post-tag relationship

Revision ID: f5c9a5432e0
Revises: 374bd75b2fad
Create Date: 2013-07-21 23:12:39.143024

"""

# revision identifiers, used by Alembic.
revision = 'f5c9a5432e0'
down_revision = '374bd75b2fad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.create_table('post_tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint()
    )

    ### end Alembic commands ###


def downgrade():
    op.drop_table('post_tags')
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint()
    )

    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
